#!/bin/sh
PHP=`which php`
exec $PHP -C -q -d output_buffering=1 "$0" "$@"
<?php
/**
 * psop - PHP Script Optimizer
 * 
 * @author     Rutger <rutger@maaksite.nl>
 * @package    MaakSite.nl
 * @copyright  Copyright (c) 2008 MaakSite.nl Productions (http://productions.maaksite.nl)
 * @license    http://productions.maaksite.nl/Licensing     New BSD License
 * @version    $Id$
 */
require_once 'psop.php';